  
language: c
sudo: true

git:
  submodules: false

compiler:
 - gcc
env:
  global:
    # Ubuntu version
    - LINUX_DIST=trusty
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    # Global build options and C++ flags
    - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
    # Misc
    - RUN_TESTS=true
    - COVERAGE=true
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-6
    - valgrind
    - cppcheck
    - lcov
    - sloccount
    - clang++-8.0

before_install:
 - ls -las
 - export MAKEFLAGS="-j3"
 - export CXX=g++-6
 - export CC=gcc-6
 - export PATH="$PATH:/opt/riscv/bin"
 - chmod +x ./tools/download-riscv32-gcc-gdrive.sh
 - ./tools/download-riscv32-gcc-gdrive.sh
 - tar xvzf riscv-gcc.tar.gz --strip-components 2
 - export PATH=$PWD/riscv-elf/gcc-8.1.0/bin:$PATH
 - export HFOS_ROOT=$PWD
 - echo $PWD

install:
 - "[ $CXX = g++ ] && export CXX=g++-6 || true"
 - gcc -o ${TRAVIS_BUILD_DIR}/hf_riscv_sim ${TRAVIS_BUILD_DIR}/tools/sim/hf_riscv_sim/hf_riscv_sim.c # Compile the riscv simulator

script:
 # Static Analysis check
 - cppcheck ${TRAVIS_BUILD_DIR}/software/tests/ 2>&1 | grep -n --color=never \(error\) &>./error.log || true
 - if [ ! -s "./error.log" ]; then echo No Static Analysis Errors; else cat ./error.log; exit 1; fi
 - cd ${TRAVIS_BUILD_DIR}/software/tests
 - chmod +x test-all.sh && ./test-all.sh
 - bash <(curl -s https://codecov.io/bash)

after_script:
 - ls

after_success:
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --capture --output-file coverage.info # capture coverage info
- lcov --remove coverage.info 'tests/*' '/usr/*' 'test-library*' --output-file coverage.info # filter out system and test code
- lcov --list coverage.info # debug before upload
#- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls.. for a private repo using a token
- coveralls-lcov  coverage.info #for open source 
 - echo "Success"

after_failure:
 - echo "Fail"
