
language: c
compiler: gcc


install: 
  # cppcheck
  - sudo apt-get install -qq cppcheck

script: 
  # Build and run this project
  - make
  - make test
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
